### ISSUE TITLE
[FEATURE] Split `CODEOWNERS` to better identify actual code owners

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/dashboards-observability#1252]
**Is your feature request related to a problem?**
Our [current `CODEOWNERS` file](https://github.com/opensearch-project/dashboards-observability/blob/43a044fa5075eedf0ab4c232e39bd5b149c63751/.github/CODEOWNERS) currently marks every maintainer as an owner of the entire codebase. The issue is that code owners are automatically added as reviewers to PRs that touch owned code, which in practice means that every maintainer is assigned as a reviewer on every PR. This makes the review notifications very noisy and makes it harder to identify PRs where a maintainer is actually needed.

**What solution would you like?**
`CODEOWNERS` turns out to be capable of much more than a global mask, though. It supports [gitignore-like syntax](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners#codeowners-syntax) to assign owners to individual files. By making better use of this file, we can get PRs to the people that need to see them, faster. For example, for adding the integrations project's main developers, we could consider adding the line:

```
**/integrations   @Swiddis @YANG-DB 
```

Which would add only the two mentioned devs as a reviewer, since `CODEOWNERS` only applies the last matching line in a file.

It also can just reference the [opensearch-project/observability team](https://github.com/orgs/opensearch-project/teams/observability) directly instead of listing every dev, which has the benefit of better dynamic management and also would help make the review process less noisy.

```
*   @opensearch-project/observability 
```

**What alternatives have you considered?**
There are a few other approaches to the issue.
- We could just disable automatically adding code owners in the repository review settings, making the process manual. I think this would still be better than adding everyone.
- We could use a more elaborate system like [assign-reviewer-by-label](https://github.com/buildsville/assign-reviewer-by-label) to implement this functionality through PR labels instead of CODEOWNERS.

**Do you have any additional context?**
This type of strategy is put to good use in some large projects like [CPython](https://github.com/python/cpython/blob/main/.github/CODEOWNERS) and [Node.js](https://github.com/v8/node/blob/main/.github/CODEOWNERS)

**Comment by peternied** [comment]
Also see https://github.com/opensearch-project/OpenSearch/issues/10613
