### ISSUE TITLE
[BUG] Overriding OSD styles is breaking the interface

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/dashboards-observability#1393]
https://github.com/opensearch-project/dashboards-observability/blob/ea2fb2c1669a229f4a58de145db81247eaec6b18/public/components/event_analytics/explorer/sidebar/sidebar.scss#L155-L158

`.deSidebar` is a class name used by OSD and the `min-width` and `max-width` break the interface. As a result of these, the sidebar on Discover is too wide and clipped by the parent, hiding the scollbar and vital buttons.

**Comment by AMoo-Miki** [comment]
On second thought, looks like OSD has borrowed code from observability and as such, they have to change theirs.

**Comment by AMoo-Miki** [comment]
Spoke to Eric. Looks like Observability borrowed the code and will need to decouple.

**Comment by paulstn** [comment]
https://github.com/opensearch-project/dashboards-observability/blob/main/public/components/event_analytics/explorer/sidebar/sidebar.scss#L155
Naming changed, fixed
