### ISSUE TITLE
[BUG] Log Events Page for Application is empty

### ISSUE THREAD

**Issue by maxpschonder** [opensearch-project/dashboards-observability#1410]
**What is the bug?**
Log Events panel is not opening the Log Explorer.

**How can one reproduce the bug?**
1. Go to 'https://playground.opensearch.org/app/observability-applications#/S7-XIowB4v5SU7kSFV7Y'
2. Click on 'Log Events'
4. See empty page

**What is the expected behavior?**
The Log Explorer should open.

**What is your host/environment?**
 - OS: macOS 14.2.1
 - Firefox 122.0

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/dashboards-observability/assets/76944068/5898d7e1-7c8d-4ba5-8b47-dee588eb9f67)

**Do you have any additional context?**
This happens since 2.11.0 and happens also in our self-hosted OpenSearch instance.

**Comment by Swiddis** [comment]
Looks like this is fixed in the latest playground.
