### ISSUE TITLE
[BUG] Cannot create observability dashboard after creating with invalid name

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/dashboards-observability#1466]
**What is the bug?**
Cannot create observability dashboard after creating with invalid name

**How can one reproduce the bug?**
1. Go to https://playground.opensearch.org/app/observability-dashboards#/
2. Click on create dashboard
3. Click on create
4. See error `Invalid Dashboard name`
5. Click on create again, nothing happens

**What is the expected behavior?**
dialog asking user to input name

**What is your host/environment?**
 - OS: [e.g. iOS] linux
 - Version [e.g. 22] 2.12
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by Mahima081** [comment]
Hi team,
Please assign this bug to me. I'm working on it and will be raising a PR shortly.
Thanks!

**Comment by anirudha** [comment]
All set! Send in PRs we can chat if you need help or be on a pairing session

**Comment by Mahima081** [comment]
@anirudha @joshuali925 I've raised a PR to fix this bug. Please review and let me know in case of any changes.

**Comment by joshuali925** [comment]
closing since #1730 is merged. thanks!
