### ISSUE TITLE
Adjust styling for remove button in panel search bar

### ISSUE THREAD

**Issue by eugenesk24** [opensearch-project/dashboards-observability#16]
Weird x is showing up when typing in panels search bar for clearing all
<img width="1792" alt="Screen Shot 2022-03-31 at 4 31 44 PM" src="https://user-images.githubusercontent.com/92330893/161166105-1ae7a1cf-a023-4561-b406-466ab85c2890.png">

**Comment by Swiddis** [comment]
Doesn't appear nowadays
![grafik](https://github.com/opensearch-project/dashboards-observability/assets/31739405/e15f77ff-bd82-40ea-98a1-dd9c42c93f72)
