### ISSUE TITLE
[BUG] [object Object] is not valid JSON in prometheus metrics

### ISSUE THREAD

**Issue by shotor** [opensearch-project/dashboards-observability#1665]
**What is the bug?**
A clear and concise description of the bug.

I added Prometheus as a data source. But when I go to `/app/observability-metrics` I see a quick flash of the metrics in the sidebar and then the content goes blank with a JS error in the console:

```js
VM206:1 Uncaught (in promise) SyntaxError: "[object Object]" is not valid JSON
    at JSON.parse (<anonymous>)
    at displayVisualization (observabilityDashboards.plugin.js:1633:114610)
    at observabilityDashboards.chunk.4.js:1:411757
    at Object.fa [as useMemo] (osd-ui-shared-deps.js:435:61568)
    at t.useMemo (osd-ui-shared-deps.js:419:5984)
    at VisualizationContainer (observabilityDashboards.chunk.4.js:1:410467)
    at $i (osd-ui-shared-deps.js:435:57931)
    at Na (osd-ui-shared-deps.js:435:66792)
    at gs (osd-ui-shared-deps.js:435:105389)
    at uc (osd-ui-shared-deps.js:435:96718)
```

I put a breakpoint in `displayVisualization (observabilityDashboards.plugin.js:1633:114610)`

And I can see that `metaData.userConfigs` is a JavaScript object and not a string.

```js
metaData.userConfigs = JSON.parse(metaData.userConfigs)
```

If I remove the `JSON.parse` in my Chrome devtools I can see the metrics in the sidebar. When I click a metric it goes blank again because my Chrome devtools is not making the change persistent. Not sure how to do that.

From source:
https://github.com/opensearch-project/dashboards-observability/blob/2d1672726efec347d0d90e4ca9273675d9a0209c/public/components/custom_panels/helpers/utils.tsx#L714

An easy fix would be to check if it's already an object. But not sure why the expected value is string. 

**How can one reproduce the bug?**

1. Add Prometheus metrics datasource
2. Click on it
3. Click on `Query Data`

**What is the expected behavior?**

It should show the metrics

**What is your host/environment?**
 - OS: debian12
 - Docker 25.0.5
 - Version 2.12.0

**Do you have any additional context?**

I'm getting metrics from:

- cAdvisor
- Metrics from the Prometheus instance itself

**Comment by Swiddis** [comment]
Thanks for the bug report! Tried following the refs to derive what the intended type is and it does look like it's inconsistently being used as a string and object. In a similar position: I tried refactoring to make a safer userConfig parser

```ts
const parseMetadataUserConfig = (
  userConfigs?: string | SavedObjectAttributes
): SavedObjectAttributes => {
  if (userConfigs === undefined || userConfigs === '') {
    return {};
  } else if (typeof userConfigs === 'string') {
    return JSON.parse(userConfigs);
  } else {
    return userConfigs;
  }
};

export const displayVisualization = (
  metaData: SavedVisualizationType | undefined,
  data: ExplorerData | undefined,
  type: string
) => {
  if (metaData === undefined || isEmpty(metaData)) {
    return <></>;
  }

  metaData.userConfigs = parseMetadataUserConfig(metaData.userConfigs);
  
  // And refactoring all the redundant spreads:
  const dataConfig = metaData.userConfigs?.dataConfig || {};

  // ...
}
```

And it seems to work to clear out most type errors, but I'm also missing context on what the prometheus flow should look like to begin with. Will see if I can find someone who knows it better.

**Comment by Swiddis** [comment]
More prometheus issues that came up in 2.13:
- https://github.com/opensearch-project/sql/issues/2601
- https://github.com/opensearch-project/dashboards-observability/issues/1666

Looks like this is a testing blindspot. Assigning this to myself and @RyanL1997 for these issues and improving our testing.

**Comment by akshatmisra198808** [comment]
There is a bug for this created with all the details https://github.com/opensearch-project/sql/issues/2541

**Comment by Swiddis** [comment]
Completed by #1757 and ready to go for 2.14
