### ISSUE TITLE
[ACTION NEEDED] Fix flaky integration tests at distribution level

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/dashboards-observability#1670]
**What is the bug?**
It was observed in 2.13.0 and previous other releases that this component manually signed off on the release for failing integration tests. See https://github.com/opensearch-project/opensearch-build/issues/4433#issuecomment-2026486279
The flakiness of the test runs take a lot of time from the release team to collect go/no-go decision and significantly lower the confidence in the release bundles.

**How can one reproduce the bug?**
1. Run integration testing for altering and see the failures. 
2. Issues can be reproduced using the steps declared in AUTOCUT issues for failed integration testing

**What is the expected behavior?**
Tests should be consistently passing.

**Do you have any additional context?**
Please note that this is a hard blocker for 2.14.0 release as per the discussion [here](https://github.com/opensearch-project/opensearch-build/issues/4588)

**Comment by Swiddis** [comment]
It also looks like many of the manifests are still showing a `Not Available` status, related to the discussion [here](https://github.com/opensearch-project/dashboards-observability/issues/1047#issuecomment-2043209817), but it's showing them even for fresh logs so it doesn't seem to be an issue of the manifests being stale.

**Comment by bbarani** [comment]
Tagging @zelinh here to provide his inputs.

**Comment by zelinh** [comment]
Here are some reasons that it may show `Not Available`. https://github.com/opensearch-project/opensearch-build/tree/main/src/report_workflow#why-are-some-component-testing-results-missing-or-unavailable
@Swiddis Could you share one situation that is showing `Not Available` so I can look into it in more details.

**Comment by Swiddis** [comment]
>  Could you share one situation that is showing Not Available so I can look into it in more details.

E.g. the [2.14 integration tests autocut](https://github.com/opensearch-project/dashboards-observability/issues/1702), of the three most recent manifests at the time of writing, two of them are unavailable ([most recent](https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7605/linux/x64/rpm/test-results/5856/integ-test/test-report.yml), [second most recent (available)](https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7603/linux/x64/rpm/test-results/5851/integ-test/test-report.yml), [third most recent](https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7601/linux/arm64/deb/test-results/5844/integ-test/test-report.yml)).

**Comment by zelinh** [comment]
> > Could you share one situation that is showing Not Available so I can look into it in more details.
> 
> E.g. the [2.14 integration tests autocut](https://github.com/opensearch-project/dashboards-observability/issues/1702), of the three most recent manifests at the time of writing, two of them are unavailable ([most recent](https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7605/linux/x64/rpm/test-results/5856/integ-test/test-report.yml), [second most recent (available)](https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7603/linux/x64/rpm/test-results/5851/integ-test/test-report.yml), [third most recent](https://ci.opensearch.org/ci/dbc/integ-test-opensearch-dashboards/2.14.0/7601/linux/arm64/deb/test-results/5844/integ-test/test-report.yml)).

I saw these in both of the unavailable runs. Seems like the process is terminated because of timeout limit when we run the integ tests for observabilityDashboards ; therefore it didn't run through all the test recording process. 
```
Cancelling nested steps due to timeout
Sending interrupt signal to process

Session terminated, killing shell...Terminated
 ...killed.
script returned exit code 143
```
https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/5856/consoleFull
https://build.ci.opensearch.org/job/integ-test-opensearch-dashboards/5844/consoleFull
Both of these jobs run for more than 4 hours; while the available one run only 1.5 hour.
Do you have any idea why these jobs run longer than usual? @rishabh6788 @gaiksaya

**Comment by Swiddis** [comment]
Hypothesis: The failing tests are flaky and the timeouts only happen if the tests pass (i.e. something later in the test suite is taking all the time). We only get the failure message when the earlier test fails and cuts the run short. Based on this hypothesis I made https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/1250 to fix the flakiness, but I'm still not sure what's causing the timeouts.

**Comment by Swiddis** [comment]
For completeness I've checked the recent pipeline logs after the flakiness fix was merged, and am not seeing any integ-test failures for observability. https://build.ci.opensearch.org/blue/rest/organizations/jenkins/pipelines/integ-test-opensearch-dashboards/runs/5899/log/?start=0

I can find the interruption exception, but not the indication of what specifically is being interrupted (is some test hanging?):

```
org.jenkinsci.plugins.workflow.actions.ErrorAction$ErrorId: 5a075705-b450-4433-85c4-0b5d9991ba84
org.jenkinsci.plugins.workflow.steps.FlowInterruptedException
		at org.jenkinsci.plugins.workflow.steps.BodyExecution.cancel(BodyExecution.java:59)
		at org.jenkinsci.plugins.workflow.steps.TimeoutStepExecution.cancel(TimeoutStepExecution.java:197)
		at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
		at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
		at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
		at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	Caused: java.lang.Exception: Error running integtest for component observabilityDashboards
		at WorkflowScript.run(WorkflowScript:317)
		at org.jenkinsci.plugins.docker.workflow.Docker$Image.inside(Docker.groovy:141)
		at ___cps.transform___(Native Method)
		at java.base/jdk.internal.reflect.GeneratedConstructorAccessor790.newInstance(Unknown Source)
```

**Comment by bbarani** [comment]
Tagging @rishabh6788 to look in to the above failure ^

**Comment by Swiddis** [comment]
Currently just held up by #1822
