### ISSUE TITLE
[FEATURE] JSON5 support for integration config files

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/dashboards-observability#1680]
**Is your feature request related to a problem?**
[JSON5](https://json5.org/) is an extension of JSON that makes it easier for humans to work with, for scenarios like config files. Among other things this includes:
- Comments
- No need to quote keys
- Multiline strings
- Trailing comma support

Integrations currently uses JSON to store all of its config data, which isn't terrible but also isn't ideal.

**What solution would you like?**
It would be nice to support JSON5 for [integration config files](https://github.com/opensearch-project/dashboards-observability/blob/main/docs/integrations/config.md), since these are typically written by hand by integration developers.

**What alternatives have you considered?**
We could use alternative formats like TOML or YAML, but that seems like a more drastic change. It probably wouldn't be a massive migration since we could have backwards-compatible JSON support, but it would be more complex and require maintaining both serializations. JSON5 is a more drop-in replacement that still has some nice ease-of-use additions.

**Do you have any additional context?**
Marking this as "Good First Issue" since most of the work is replacing the import in the [Integration file reader](https://github.com/opensearch-project/dashboards-observability/blob/main/server/adaptors/integrations/repository/fs_data_adaptor.ts) and [Integration JSON reader](https://github.com/opensearch-project/dashboards-observability/blob/main/server/adaptors/integrations/repository/json_data_adaptor.ts), give or take some more CTRL+F for `JSON.parse` refs.

**Comment by devesh-2002** [comment]
May I take up this issue?

**Comment by Swiddis** [comment]
By all means!

**Comment by Swiddis** [comment]
Completed by #1732
