### ISSUE TITLE
[BUG] [Metric Analytics] when span interval is changed some of the visualizations throws error

### ISSUE THREAD

**Issue by mengweieric** [opensearch-project/dashboards-observability#169]
[Metric Analytics] when span interval is changed some of the visualizations throws error, the behavior is not consistent though

![Image](https://user-images.githubusercontent.com/80358241/210863585-04203779-7720-40e7-9054-c8ef19bfa06b.png)

**Comment by mengweieric** [comment]
For query like `source = prometheus.promhttp_metric_handler_requests_total | where @timestamp >= '2023-01-01 08:00:00.000000' and @timestamp <= '2024-01-01 07:59:59.999000' | stats avg(@value) by span(@timestamp,1h)` in panel where this year is selected, it gets `{
    "statusCode": 503,
    "error": "Service Unavailable",
    "message": "{\n  \"error\": {\n    \"reason\": \"There was internal problem at backend\",\n    \"details\": \"Request to Prometheus is Unsuccessful with : the query time range exceeds the limit (query length: 8759h59m59s, limit: 768h0m0s)\",\n    \"type\": \"RuntimeException\"\n  },\n  \"status\": 503\n}"
}` need better UI error message and handlings

**Comment by ps48** [comment]
@mengweieric Are you getting this after the PR is merged?
