### ISSUE TITLE
[BUG] Trace linking from logs explorer opens a blank page 

### ISSUE THREAD

**Issue by ps48** [opensearch-project/dashboards-observability#1703]
**What is the bug?**
Event explorer feature to open traces from logs isn't working as expected. Whenever user clicks on the trace link they land on traces page with a blank screen. 

**How can one reproduce the bug?**
1. Add sample trace data. 
2. Create a logs index with the sample data loaded. 
3. Link on traces link to load trace analytics UI. 

**Work-around** 
1. The current work around is to manually update the link 
```
From: 
https://search-endpoint/_dashboards/app/observability-traces#/15d30e4d211d79e10fcaeab97015c90d

To: 
https://search-endpoint/_dashboards/app/observability-traces#/traces/15d30e4d211d79e10fcaeab97015c90d
```

**What is the expected behavior?**
1. The URL needs to be fixed for the redirection. 
2. Need to increase test coverage to not have such regression in future.

**What is your host/environment?**
 - OS: linux
 - Version: 2.11 
 - Plugins: dashboards-observability

**Do you have any screenshots?**
![Screenshot 2024-04-16 at 11 06 36 AM](https://github.com/opensearch-project/dashboards-observability/assets/4348487/371b2dbc-7693-4526-b531-4cecde97dff4)
![Screenshot 2024-04-16 at 11 06 49 AM](https://github.com/opensearch-project/dashboards-observability/assets/4348487/860a5ab7-ff41-48d2-963b-d143703ad9de)

**Do you have any additional context?**
Add any other context about the problem.

**Comment by paulstn** [comment]
Fixed by external contributor: https://github.com/opensearch-project/dashboards-observability/pull/1390
