### ISSUE TITLE
[BUG]Metrics Analysis Not showing Single datapoint result from Prometheus Metrics 

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#1758]
**What is the bug?**
Once the span resolution becomes too wide and a single result is returned from the metrics
The graph doesn’t show the single datapoint in a clear way

**How can one reproduce the bug?**
-- See attached movie top reconstruct the steps

**What is the expected behavior?**
A single datapoint should be very apparently visible

**Do you have any screenshots?**

https://github.com/opensearch-project/dashboards-observability/assets/48943349/87fb8995-ccaf-41aa-a950-5501b630993a

**Comment by Swiddis** [comment]
Should this be triaged to OSD core? I'm not sure if the logic for drawing visualizations is here or in the panel itself.
