### ISSUE TITLE
[BUG] Trace not loading if opened directly in new tab

### ISSUE THREAD

**Issue by joshuali925** [opensearch-project/dashboards-observability#269]
**What is the bug?**
Trace page is blank if opened from URL, possibly due to jaeger integration and not changing from jaeger to data-prepper. cc: @derek-ho 

**How can one reproduce the bug?**
1. Chrome open new tab
2. Paste `http://localhost:5601/app/observability-dashboards#/trace_analytics/traces/8832ed6abbb2a83516461960c89af49d`, where `8832ed6abbb2a83516461960c89af49d` is a valid data-prepper trace ID
3. Page loads but no data

**What is the expected behavior?**
This worked in 2.3, not working in 2.5

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by derek-ho** [comment]
PR above should fix this issue for people with only one type of data - need to create follow up PR for folks with both types - check if specific trace/service exists
