### ISSUE TITLE
[BUG] View Surrounding logs doesn't work on Application analytics

### ISSUE THREAD

**Issue by arunx2** [opensearch-project/dashboards-observability#27]
**Describe the bug**
View Surrounding logs doesn't work on Application analytics. 

**To Reproduce**
1. Create application on Application dashboard. 
2. Go into Application
3. Click on "log events"
4. Select any log entry in the below section.
5. Click on "view surrounding logs" on top right corner
6. See error that no logs are listed around that.

This works as expected on "event analytics" 

**Expected behavior**
View surrounding logs should be listed instead of "issue in building surrounding data query"

**OpenSearch Version**
2.3

**Dashboards Version**
2.3

**Plugins**

Please list all plugins currently enabled.

**Screenshots**

![2022-11-08_15-53-50 (1)](https://user-images.githubusercontent.com/844111/200725377-fcf1deb0-d2be-4bab-ba7d-53558e686567.gif)

**Host/Environment (please complete the following information):**
 - OS: Docker image on EKS
 - Browser and version Firefox 

**Additional context**

**Comment by Swiddis** [comment]
Looks like this wasn't closed with the above PR, closing now.
