### ISSUE TITLE
Baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions

### ISSUE THREAD

**Issue by dblock** [opensearch-project/dashboards-observability#275]
Follow https://github.com/opensearch-project/.github/issues/125 to baseline MAINTAINERS, CODEOWNERS, and external collaborator permissions.

Close this issue when:

1. [MAINTAINERS.md](MAINTAINERS.md) has the correct list of project maintainers.
2. [CODEOWNERS](CODEOWNERS) exists and has the correct list of aliases.
3. Repo permissions only contain individual aliases as collaborators with maintain rights, admin, and triage teams. 
4. All other teams are removed from repo permissions.

If this repo's permissions was already baselined, please confirm the above when closing this issue.

**Comment by dblock** [comment]
Your permissions are incorrect. You have 19 people with admin access.

![Screenshot 2023-04-04 at 12 03 29 PM](https://user-images.githubusercontent.com/542335/229851024-1b444dae-d32f-4bff-bd21-20578a7126ea.png)

Please work with an admin to adjust permissions.

**Comment by anirudha** [comment]
working with current admins to resolve this and baseline the permissions

**Comment by bbarani** [comment]
Added the users listed in MAINTAINERS.md file as maintainers of this repo. @anirudha @derek-ho Please add CODEOWNERS file under .github directory with the maintainers list.

**Comment by dblock** [comment]
Verified, thx.
