### ISSUE TITLE
[BUG] GitHub workflow uses the range of `engines.node` and `engines.yarn` from OSD wrongly

### ISSUE THREAD

**Issue by AMoo-Miki** [opensearch-project/dashboards-observability#290]
**What is the bug?**
https://github.com/opensearch-project/dashboards-observability/blob/0527730d9c7a7743e03061048937c6b3aa611788/.github/workflows/dashboards-observability-test-and-build-workflow.yml#L35-L36

OSD provides a range in `engines` that works for OSD without considering deps or plugins. Sometimes, dependencies require higher versions of Yarn or Node.js and that is NOT reason enough for OSD to bump their `engines`. hence, the CI needs to use a version that works and will need to make adjustments deps evolve.

There is a counter argument that could be made that the lockfile dictates what OSD uses so it should make the best effort to satisfy those deps. I would argue against it that OSD plugins have deps that might not be common with OSD and those deps could impose their own `engines`; OSD cannot be expected to kep up with those.

**Solution**
Just like OSD does it, hardcode the version of Yarn. OSD uses `nvm` and `.nvmrc`; you could do the same, read the version from `.nvmrc`, or hardcode your own version of Node.js in the CI.

**Comment by joshuali925** [comment]
closed by #295
