### ISSUE TITLE
[DESIGN] how to serve Logos and Other Images

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-observability#332]
**Problem Statement:** 
In order to have the best possible experience for integrations we need to be able to show logos and screenshots of the dashboards to be imported for each integration. This will help with discoverability and trust of the new community contributions. However, this poses many problems with how we serve these images and where they are hosted/stored. 

There are two main options: 
- **Bundle these assets with the distribution** 
_Pro:_
- Doesn't need internet connection to be able to retrieve these images
_Con:_
- Assets will be tied to versioned release process

- **Host them somewhere else**
_Pro:_
- Contributions can be decoupled from the versioning process 
_Con:_
- Assumes internet connection to be able to retrieve these images

--------------------------------------------------------------------------------------------------------------------------

***For 2.7, we are going with bundling it in the distribution, CDN/other options can be considered later as a target state.***

# Proposed Implementation of Bundling:
### High level Overview:
- Store SVG/assets as blobs in opensearch on load of the backend plugin
- Return binary to UI as part of payload
- UI renders binary
- need to look into base64 encoding and other stuff necessary to make this work

## Alternatives/Questions: 
- Any other ways of solving this problem? One is below...

# Proposed Alternative Implementation of Bundling:
### High Level Overview:
- Assets will be contributed to Observability/Integration Front End Plugin (including a default, fallback logo)
- Observability/Integration will register these assets as urls on the localhost route: (for example at: http://localhost:5601/ui/integrations/nginx.svg) on plugin startup
- Observability Backend will return the URL following the agreed upon URL, and integrations front end will fetch the assets from the locally hosted url. If the url does not exist on the entry, we will use the fallback logo

### Details:
- A similar approach is done in dashboards core:
```
coreSetup.http.registerStaticDir('/ui/{path*}', Path.resolve(__dirname, './assets'));
    coreSetup.http.registerStaticDir('/ui/assets/{path*}', fromRoot('assets'));

    coreSetup.http.registerStaticDir(
      '/node_modules/@osd/ui-framework/dist/{path*}',
      fromRoot('node_modules/@osd/ui-framework/dist')
    );
```
This registers routes for all assets in the folder, and allows them to be fetched, for example with:
```
<img src='http://localhost:5601/ui/default_branding/opensearch_logo_default_mode.svg'/>
```

## Limitations:
- This design doesn't allow for user - made integrations logo and screenshot contributions (since we assume the assets are bundled as part of the front-end plugin (is this ok for 2.7?))

## Cons:
- Assumes tight coupling between backend and frontend plugins 

## Alternatives/Questions: 
- - Can we not return url and check on the front end if a given asset exists (for example for nginx check if http://localhost:5601/ui/integrations/nginx.svg exists, and use a fallback logo if it does not)

**Comment by anirudha** [comment]
this is ok for 2.7/ We need to create a process for custom loading in upcoming releases
> lets ticket this in backog : Cons: - Assumes tight coupling between backend and frontend plugins

**Comment by Swiddis** [comment]
> Con: Assets will be tied to versioned release process
I don't follow why this is a con

**Comment by Swiddis** [comment]
My only concern with the design as-stated is that the exact asset URL should be clarified. I assume `/ui/integrations` is a placeholder for individual paths that will be assigned per-integration, but if so, I want to see where the front-end will get that path from. (My understanding is that integration IDs are assigned dynamically.) Or if it is one central path, then I want to know how we avoid name collisions across different integrations.

**Comment by YANG-DB** [comment]
`Assets will be contributed to Observability/Integration Front End Plugin` - I think it will be much more complicated for contributing a single Integration into two different repos (F/E , B/E ) ...
- why not just go with the first suggested alternative - all Integration assets are loaded from plugin bundle folder [Integration](https://github.com/opensearch-project/observability/tree/2.x/integrations) directly into a `repository` index which represents the available `integration-templates` that can be loaded.
- the `repository` index can contain both json files, images (blobs) and documents (html)
- All this content will be served via a REST API on the inital F/E call and afterwards would be cached in the browser local store for performance

**Comment by derek-ho** [comment]
> `Assets will be contributed to Observability/Integration Front End Plugin` - I think it will be much more complicated for contributing a single Integration into two different repos (F/E , B/E ) ...
> 
> * why not just go with the first suggested alternative - all Integration assets are loaded from plugin bundle folder [Integration](https://github.com/opensearch-project/observability/tree/2.x/integrations) directly into a `repository` index which represents the available `integration-templates` that can be loaded.
> * the `repository` index can contain both json files, images (blobs) and documents (html)
> * Integration's content will be served via a REST API on the initial F/E call and afterwards would be cached in the browser local store for performance

This seems cleaner on second thought. I have never worked with rendering blobs on UI, so it will be a good learning experience :)

**Comment by ps48** [comment]
The Option 2 shouldn't be the option to go, in my opinion. It will add another dependency to OSD. We don't want the community to host a third component just to save assets elsewhere. 

I may not be understanding the workings here between F/E and B/E for integrations. Can you explain more details on this? Ideally, you just need an integration `uuid` from the B/E. Also, I think dashboards core way of routing assets is the way to go.

**Comment by derek-ho** [comment]
I don't get how dashboards core way of routing assets would work if we store the assets on the backend? @ps48 lets have a sync up offline about this

**Comment by kgcreative** [comment]
How and where are these assets handled in the existing "Add sample data" flows?
