### ISSUE TITLE
[UPGRADE] Cypress test suite to modern version - 12.10

### ISSUE THREAD

**Issue by pjfitzgibbons** [opensearch-project/dashboards-observability#411]
**What is the bug?**

As a code-hygene concern, I would like to upgrade cypress to current version - 12.10.
Even though our cypress is technically “working”.. .the current version is 6 Majors behind… so keeping this up to date counts as basic responsible code keeping.

Your thoughts deisred.

**How can one reproduce the bug?**
1. $ yarn open cypress
2. View version on bottom-right of window - 6.9.1
3. Click-through to Cypress Changelog - scroll to 6.9.1 and see release date 4/5/2021

Debugging and troubleshooting test timing and other issues will be easier with a trusted framework version.

**What is the expected behavior?**
Update to Cypress 12.10 (change package.json, yarn.lock, upgrade cypress infrastructure.)

**What is your host/environment?**
 - Plugins

**Do you have any screenshots?**

**Do you have any additional context?**
Add any other context about the problem.

**Comment by mengweieric** [comment]
FTR currently uses cypress 9.5.4, it may be good to have the same version as theirs or posting the same request to FTR also, so that we won't have the issue of having some tests working fine on our internal cypress tests but fails in FTR.

**Comment by mengweieric** [comment]
This PR is for FTR to upgrade cypress: https://github.com/opensearch-project/opensearch-dashboards-functional-test/pull/598

**Comment by pjfitzgibbons** [comment]
@mengweieric we discussed offline.   My opinion is that the FTR test suite should be absolute minimum functional test, as it tests the entire suite in full functionality.   The FTR suite should only be testing that our plugin "is loaded" or "works" in some simple and direct test.  All real "functional" tests to our plugin should occurr within our repo and are not contained-within nor are executed-by the OpenSearch-Dashboards FTR test-run.

Given that, I feel that the Observability team should be using the most-modern tools available.  This provide the most up-to-date dependencies, which will always match the current online documentation, blogs, StackOverflow questions, etc.
This also provides the environment that is most likely to follow the "intuition" of the development team.   A developer is likely to find the use of a dependency/tool (Cypress), go look it up online, see the "current" website/documentation, and expect our codebase to behave as seen.   It is a cognitive dissonance and distraction to have to look for the "used version" of the tool and search for documentation (and blogs, StackOverflow!!) matching that version.

In the technology sector, old versions of tools/libraries/frameworks (languages!!) are forgotten online VERY QUICKLY.

We need to do ourselves (well, my forgetful self at least), our new-developers, and our community members a favor and provide the best tooling possible for our development environment.

**Comment by TackAdam** [comment]
In the current version of Cypress 6.9.1 all of the testing encounters the following error and fails / stops running.
 
<img width="468" alt="image" src="https://github.com/opensearch-project/dashboards-observability/assets/105462877/2f17811b-6085-45f1-a27a-671a0e00de67">

The only solution I have been able to find to stop this error is removing the “cypress-watch-and-reload:”^1.10.6” from devDependencies in package.json.
 
To counteract this, I believe the best solution is to upgrade to the newest version of Cypress or at a minimum the version the functional test is migrating to 12.8.1. From testing locally this error is not present in the upgraded Cypress options.

**Comment by TackAdam** [comment]
Created PR to upgrade to 12.8.1
https://github.com/opensearch-project/dashboards-observability/pull/468

**Comment by derek-ho** [comment]
Closing as done
