### ISSUE TITLE
[BUG] Version failure

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-observability#474]
Got the following when trying to download insights dashboards plugins onto OSD @TackAdam this might be due to the recent cypress version bump?

ERROR [single_version_dependencies] Multiple version ranges for the same dependency
      were found declared across different package.json files. Please consolidate
      those to match across all package.json files. Different versions for the
      same dependency is not supported.

      If you have questions about this please reach out to the operations team.

      The conflicting dependencies are:

        cypress
          ^12.8.1 => observability-dashboards
          ^5.0.0 => opensearch-query-workbench, reports-dashboards
        husky
          6.0.0 => observability-dashboards
          ^4.2.5 => opensearch-query-workbench
        lint-staged
          ^13.1.0 => observability-dashboards
          ^10.2.0 => opensearch-query-workbench
        ts-jest
          ^29.1.0 => observability-dashboards
          ^26.1.0 => opensearch-query-workbench, reports-dashboards

**Comment by ananzh** [comment]
https://github.com/opensearch-project/OpenSearch-Dashboards/pull/4071 support node 14, 16 and 18. Pls test on node 18. 
```
nvm install 18.16.0
nvm use 18.16.0
```
