### ISSUE TITLE
[INTEGRATION] AWS VPC Flow Log Integration

### ISSUE THREAD

**Issue by wanghd89** [opensearch-project/dashboards-observability#642]
**Is your feature request related to a problem?**
The integration project doesn't have content to demonstrate how AWS VPC flow log looks like in Opensearch Dashboard

**What solution would you like?**
Create VPC Flow log schema, list of visual and query based assets including the dashboard, sample data.

**What alternatives have you considered?**
N/A

**Do you have any additional context?**
https://docs.aws.amazon.com/solutions/latest/centralized-logging-with-opensearch/vpc-flow-logs.html#sample-dashboard-6

**Comment by YANG-DB** [comment]
Great 👍
Please also if possible add some example of setting up an end to end pipeline including the agent collector and an ingesting component pushing data into the cluster

**Comment by YANG-DB** [comment]
please feel free to start working on the PR in draft mode so we can collaborate and discuss it during development
