### ISSUE TITLE
[INTEGRATIONS-Tracking] Tracking Integrations Content

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/dashboards-observability#668]
**Is your feature request related to a problem?**

The integrations plugin has been introduced, but doesn't include content. This is a general tracking issue for work-in-progress integrations, and will also be a central point of reference to find content on creating integrations.

**Integration Issue Template:**

-   Expected source & target schema (AWS / OTEL / ECS )
-   Potential agents (OTEL receiver / Fluent-Bit / Beats / …)
-   Available dashboards (Any one of the sources we know )
-   Important fields that we want to monitor/aggregate
-   Additional questions / issues that are unclear

**Current Integration Issues:**
- #772 
   - #864
- #698
  - #866
- #669 
- #754 
   - #865  
-  #756
   - #867
- #689 
   - #868
- #773
   - #869
- #694 
- #741
  - #870 
- #702 
- #706 
- #707 : #829 
   - #873
- #710 
- #788
  -  #871
- #779
  - #872  
- #789 : #790
- #817  

**How to request an Integration ?**
Suggest / request an Integration by submitting an [Integration Issue request](https://github.com/opensearch-project/dashboards-observability/issues/new?assignees=&labels=integration%2C+untriaged&projects=&template=integration_request.md&title=%5BIntegration%5D)

**How to create integrations?**
See the [Integration Creation Guide](https://github.com/opensearch-project/dashboards-observability/wiki/Integration-Creation-Guide).

**Additional resources for creating integrations?**
See the [Integration Creation Reference](https://github.com/opensearch-project/dashboards-observability/wiki/Integration-Creation-Reference).

**Do you have any additional context?**
Integrations RFC: #644

**Comment by anirudha** [comment]
https://github.com/aws-samples/siem-on-amazon-opensearch-service

**Comment by wanghd89** [comment]
https://aws.amazon.com/solutions/implementations/centralized-logging-with-opensearch/
The AWS Solution for centralized logging

**Comment by YANG-DB** [comment]
Anyone that wants a new integration to be developed or is willing to contribute one - please open a dedicated `integration suggestion` github issue [here](https://github.com/opensearch-project/dashboards-observability/issues/new?assignees=&labels=integration%2C+untriaged&projects=&template=integration_request.md&title=%5BIntegration%5D)

**Comment by YANG-DB** [comment]
https://github.com/opensearch-project/dashboards-observability/assets/48943349/7751a7da-456d-4cbd-bc48-322ade87074d

https://github.com/opensearch-project/dashboards-observability/wiki/Integration-Documentation-Reference
