### ISSUE TITLE
[INTEGRATIONS] Integration for System Metric Logs.

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/dashboards-observability#669]
**Is your feature request related to a problem?**
Inspired heavily by [the USE method](https://www.brendangregg.com/usemethod.html) and the fantastic metric dashboards available from [MetricBeats](https://github.com/elastic/beats/tree/main/metricbeat), this issue is for creating an integration to display system metric logs in OpenSearch Dashboards.

**What solution would you like?**
An integration that implements some or most of the functionality available from MetricBeats, and possibly additional functionality that hasn't been added.

**Integrations Checklist**
- Schemas:
  - Source schema: unknown
  - Target schema: unknown
- Potential agents:
  - [ ] OTEL
  - [ ] FluentBit
  - [X] Beats
  - [ ] Other (Please specify)
- Available Dashboards:
  - [MetricBeats](https://github.com/elastic/beats/tree/master/metricbeat)
- Important fields:
  - Unknown

**Do you have any additional context?**
See: #668

**Comment by YANG-DB** [comment]
Please follow this [semantic convention ](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/semantic_conventions/system-metrics.md)
