### ISSUE TITLE
[INTEGRATIONS] Integration for S3 Access Logs

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/dashboards-observability#684]
**Is your feature request related to a problem?**
This issue is for creating an integration to display S3 access logs in OpenSearch Dashboards.

**What solution would you like?**
An integration that ingests S3 logs and implements relevant visualizations.

**Integrations Checklist**
- Schemas:
    - Source schema: [Guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/LogFormat.html#log-record-fields)
        - [Example log records](https://docs.aws.amazon.com/AmazonS3/latest/userguide/LogFormat.html)
    - Target schema: unknown
- Potential agents:
    - [ ] OTEL
    - [x] FluentBit
    - [ ] Beats
    - [ ] Other (Please specify)
- Available Dashboards:
    - [Siem S3 Access Logs Dashboard](https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/source/saved_objects/each-dashboard/s3accesslog.ndjson)
    - Important fields:
        - Unknown
 
**Do you have any additional context?**
- See #668

**Comment by YANG-DB** [comment]
<img width="908" alt="s3 logs dashboard" src="https://github.com/opensearch-project/dashboards-observability/assets/48943349/30349f57-1000-45fb-bfbb-8a011237e934">
