### ISSUE TITLE
[Documentation]update readme file to reflect recent updates and changes to the plugin

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#690]
**Is your feature request related to a problem?**
The existing README file is old and missing recent changes to our repo such as metrics Analytics and Itegrations

**What solution would you like?**
Update the readme file to reflect latest developments

**What alternatives have you considered?**

**Do you have any additional context?**
 - https://github.com/opensearch-project/dashboards-observability/wiki

**Comment by derek-ho** [comment]
@YANG-DB closing because you completed this in #691 , feel free to re-open if that's not the case
