### ISSUE TITLE
[Integration] Amazon RDS

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/dashboards-observability#695]
**What is the integration resource ?**

[Amazon Relational Database Service](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Welcome.html) is a popular managed database service that supports various popular database engines like MySQL, MariaDB, PostgreSQL, Oracle, and Microsoft SQL Server.

**What is the integration source protocol ?**

For MySQL and MariaDB logs, [error logs](https://dev.mysql.com/doc/refman/8.0/en/error-log-format.html), general query logs, slow query logs, and audit logs.

**What is the integration target protocol ?**

Unknown

**Which agents would you use to ship this data ?**

Fluent-bit. Siem has an ingestor for MySQL and MariaDB logs ([here](https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/source/lambda/es_loader/siem/sf_rds_mysql_error.py) and [here](https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/source/lambda/es_loader/aws.ini)). 

**Would you be using an ingestion pipeline ?**

Unsure

**Which Dashboards would you be using ?**

Dashboard:

![dashboard](https://github.com/opensearch-project/dashboards-observability/assets/48943349/e5fc9f37-b69e-4c83-a459-b030c297fd6e)

----

**Do you have any additional context?**

#668

**Comment by YANG-DB** [comment]
https://github.com/opensearch-project/dashboards-observability/assets/48943349/89ea5a51-3e77-45f8-b8b5-d5c0c0108c2c
