### ISSUE TITLE
[Integration] Amazon ElastiCache 

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/dashboards-observability#702]
**What is the integration resource ?**

Amazon ElastiCache is a managed in-memory caching service.

**What is the integration source protocol ?**

[`Slowlog and Engine log`](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/Log_Delivery.html).

**What is the integration target protocol ?**

Unknown

**Which agents would you use to ship this data ?**

Fluent-bit. Logs can be streamed to Amazon Kinesis Data Firehose or Amazon CloudWatch Logs.

**Would you be using an ingestion pipeline ?**

Unknown.

**Which Dashboards would you be using ?**

Unknown

----

**Do you have any additional context?**

#668

**Comment by derek-ho** [comment]
Done
