### ISSUE TITLE
[Integration] K8s

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/dashboards-observability#707]
**What is the integration resource ?**

Kubernetes, or K8s, is a system for automating deployment, scaling, and management of containerized applications. 

**What is the integration source protocol ?**

Documentation for KSM (kube-state-metrics) for Kubernetes metrics generation is [here](https://github.com/kubernetes/kube-state-metrics#metrics-documentation).

**What is the integration target protocol ?**

Unknown.

**Which agents would you use to ship this data ?**

[Fluent-bit supports Kubernetes](https://docs.fluentbit.io/manual/installation/kubernetes). Opentelemetry also supports receivers for [k8s cluster metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sclusterreceiver), [object metrics](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8sobjectsreceiver), and [events](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver/k8seventsreceiver).

**Would you be using an ingestion pipeline ?**

Unknown. 

**Which Dashboards would you be using ?**

[Beats Dashboard](https://github.com/elastic/beats/tree/f52d38ac56a752e6a22ef1ff423a990187b1d735/metricbeat/module/kubernetes)

----

**Do you have any additional context?**

#668

**Comment by derek-ho** [comment]
Done with @YANG-DB , closing
