### ISSUE TITLE
[Integration] MySQL

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/dashboards-observability#710]
**What is the integration resource ?**

MySQL is an open-source relational database management system.

**What is the integration source protocol ?**

For each type of MySQL log:

- [General Query Logs](https://dev.mysql.com/doc/refman/8.0/en/query-log.html) that keeps a general record of what MySQL is doing (more info on format [here](https://dba.stackexchange.com/questions/42532/format-of-mysql-query-log))
- [Error Logs](https://dev.mysql.com/doc/refman/8.0/en/error-log-format.html), problems encountered when starting, running, or stopping MySQL
- [Binary Logs](https://dev.mysql.com/doc/refman/8.0/en/binary-log.html) that describe database changes such as table creation or changes to data (format unknown)
- [Slow Query Logs](https://dev.mysql.com/doc/refman/8.0/en/slow-query-log.html) that consists of SQL statements that take more than a certain amount of time to execute

**What is the integration target protocol ?**

Unknown

**Which agents would you use to ship this data ?**

Fluentbit

**Would you be using an ingestion pipeline ?**

Unknown

**Which Dashboards would you be using ?**

[Beats dashboard for MySQL](https://github.com/elastic/beats/tree/main/filebeat/module/mysql).

----

**Do you have any additional context?**

#668

**Comment by derek-ho** [comment]
Completed with @YANG-DB , closing
