### ISSUE TITLE
[Integration] AWS WAF

### ISSUE THREAD

**Issue by danieldong51** [opensearch-project/dashboards-observability#711]
**What is the integration resource ?**

AWS WAF is a web application firewall that lets you monitor HTTP(S) requests to your web application resource. 

**What is the integration source protocol ?**

The Log Fields are [here](https://docs.aws.amazon.com/waf/latest/developerguide/logging-fields.html), and example logs are [here](https://docs.aws.amazon.com/waf/latest/developerguide/logging-examples.html).

**What is the integration target protocol ?**

Unknown.

**Which agents would you use to ship this data ?**

Fluentbit

**Would you be using an ingestion pipeline ?**

Siem has an [ingestion pipeline](https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/source/lambda/es_loader/siem/sf_waf.py) for WAF

**Which Dashboards would you be using ?**

[Siem Dashboard for WAF](https://github.com/aws-samples/siem-on-amazon-opensearch-service/blob/main/source/saved_objects/each-dashboard/waf.ndjson)
----
![dashboard-awswaf](https://github.com/opensearch-project/dashboards-observability/assets/58446449/315fbb46-9dc4-46c5-8ffa-0415a74f1777)

**Do you have any additional context?**

#668

**Comment by Swiddis** [comment]
Unassigning from self as Aiden said he would handle it (What's his GH handle?)
