### ISSUE TITLE
[RFC] [Feature] Documentation for Integrations

### ISSUE THREAD

**Issue by Swiddis** [opensearch-project/dashboards-observability#730]
**Is your feature request related to a problem?**
Currently, there is no organized location for general documentation on the integrations codebase, and how the individual integrations function. There are a few scattered sources but they aren't especially useful for development. In particular, we're missing:
- Javadocs for most code functions
- A high-level overview of how the plugin works
- Up-to-date API documentation
- A publicly visible roadmap
- Descriptions of how individual integrations function

Currently, we have some creation documentation available in the wiki. We ideally would like to make a folder for the documentation, but since we still don't have an established integrations repository, it's tricky.

**What solution would you like?**
As a stop-gap solution for the lack of a repository, I propose we put the documentation in a new `integrations-docs` folder, maintained separately from the observability docs. This folder will contain:
- `README.md`: A high-level overview with a table of contents that directs to other documents.
- `roadmap.md`: Future planned features that don't have issues yet, just to give ideas. Flooding too many issues could harm the development of observability, so a simple tracker here may be valuable.
- `integrations`: Documents for each of the supplied integrations and their intended usage, such as `nginx` or `aws-elb`. These documents should typically contain a description of how to set up OpenSearch to correctly ingest these logs, and some ingestion pipeline.
- `usage`: How to set up pipelines to use the plugin. This can link to the catalog for schemas, and describe various setups with FluentBit, Vector, Data Prepper, or other tools. This will be important to drive adoption, and gives us a place to deposit things like the updated fluentbit converter.
- `plugin`: Documents pertaining to plugin functionality, such as the API and how to navigate the codebase. This can be especially useful since the plugin is embedded with the dashboards-observability plugin and we could use this to help with splitting them.

**What alternatives have you considered?**
For integration documentation, we could embed it directly with the provided repository. This can work, but may be difficult to find. Ideally, we want to simply move our existing code to a separate repository, this is in progress but due to other priorities may take a while.

We have some documentation in the observability repo, but I'd like to avoid making our documentation any more fragmented than it already is. We need to start focusing more on cohesion for users.

**Do you have any additional context?**
N/A

**Comment by YANG-DB** [comment]
we already support this for integration [here](https://github.com/opensearch-project/observability/tree/main/integrations)

**Comment by YANG-DB** [comment]
@Swiddis can u plz link each doc u think is necessary to an existing doc we already have in our [here](https://github.com/opensearch-project/observability/tree/main/integrations) documents folder  ?
