### ISSUE TITLE
[BUG]Update VPC integration Readme & sourceURL

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#739]
**What is the bug?**
 VPC integration Readme & sourceURL are not correctly updated 

**What is the expected behavior?**
1) update  VPC integration Readme with a screenshot of the dashboard 
2) update the sourceURL linkage to correct location of the AWS's VPC readme file

**Do you have any additional context?**
- https://github.com/opensearch-project/dashboards-observability/pull/698
- https://github.com/opensearch-project/dashboards-observability/blob/dd278ade8d4069fb355af737aa724182bf38e087/server/adaptors/integrations/__data__/repository/aws_vpc_flow/aws_vpc_flow-1.0.0.json#L9
- https://github.com/opensearch-project/dashboards-observability/blob/main/server/adaptors/integrations/__data__/repository/aws_vpc_flow/info/README.md

**Comment by Swiddis** [comment]
Closed by #740
