### ISSUE TITLE
[FEATURE] Acceleration Wizard UI

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-observability#748]
As part of the UI for flint, we want a way for users to configure acceleration on specific queries/tables/materialized views from the UI. This can be done either via configuration (data sources management), or in the context of a given query/table. This Issue is to create the acceleration wizard UI in these two situations to allow users to easily configure acceleration methods.

**Comment by YANG-DB** [comment]
can you share details on the user experience here ?

**Comment by derek-ho** [comment]
Closing since it moved to query workbench
