### ISSUE TITLE
[BUG]Integration loading of a dashboard fails for ndjson empty lines

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#757]
**What is the bug?**

Integration loading of a dashboard fails when empty spaces appear in the ndjson file

This works well in the savedObject import api 

**What is the expected behavior?**
Success loading the ndjson dashboard even if it has empty lines - fix the integration parser to trim the ndjson

**Comment by Swiddis** [comment]
Duplicate of #743
