### ISSUE TITLE
[BUG]Error validating integration

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#760]
**What is the bug?**

When attempting to view the integrations got the next error which doesn’t load these specific integration templates
```
server    log   [23:19:14.784] [info][savedobjects-service] Waiting until all OpenSearch nodes are compatible with OpenSearch Dashboards before starting saved objects migrations...
server    log   [23:19:14.812] [info][savedobjects-service] Starting saved objects migrations
server    log   [23:19:14.855] [info][plugins-system] Starting [38] plugins: [usageCollection,opensearchDashboardsUsageCollection,opensearchDashboardsLegacy,mapsLegacy,share,opensearchUiShared,legacyExport,embeddable,expressions,data,home,apmOss,savedObjects,dashboard,visualizations,visTypeVega,visTypeTimeline,visTypeTable,visTypeMarkdown,visBuilder,visAugmenter,tileMap,regionMap,inputControlVis,visualize,management,indexPatternManagement,advancedSettings,console,charts,visTypeVislib,visTypeTimeseries,visTypeTagcloud,visTypeMetric,observabilityDashboards,discover,savedObjectsManagement,bfetch]
server    log   [23:19:15.063] [info][listening] Server running at http://localhost:5601
server    log   [23:19:15.135] [info][server][OpenSearchDashboards][http] http server running at http://localhost:5601
Validation errors in aws_s3-1.0.0.json [ 'must NOT have additional properties' ]
Validation errors in nginx-1.0.1.json [ 'must NOT have additional properties' ]
Validation errors in aws_s3-1.0.0.json [ 'must NOT have additional properties' ]
Validation errors in nginx-1.0.1.json [ 'must NOT have additional properties' ]

```

**What is the expected behavior?**
A better error explaining the issues and reflecting them on the UX so that users would be able to investigate 

**Do you have any screenshots?**
None validated integration are not showing on UX

**Do you have any additional context?**
- https://github.com/opensearch-project/dashboards-observability/pull/741

**Comment by YANG-DB** [comment]
update:
removing the `link` field from the yaml config file solves the issue:
```
    "type": "logs",
    "link": "https://www.nginx.com/",
    "author": "OpenSearch",

```

**Comment by Swiddis** [comment]
The error comes from AJV, which frustratingly doesn't give specific field names when reporting that it found unexpected fields. All it says is that it found unexpected additional fields added to the named integration config files.

The validators are configured [here](https://github.com/opensearch-project/dashboards-observability/blob/main/server/adaptors/integrations/validators.ts). If AJV has a configuration option to avoid having to write our own schema traversal for validation that's ideal, but it's expected behavior that invalid integrations just don't get rendered on the front-end.

**Comment by Swiddis** [comment]
Looks like it's easy to configure: https://ajv.js.org/options.html#verbose
