### ISSUE TITLE
[BUG]Integration Try button fails creating mapping correctly

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#768]
**What is the bug?**
The Integration Try It button doesn’t create the mapping correctly

**How can one reproduce the bug?**
Select an Integration and press the Try It
1. Go to dev console
2. run `GET _component_template` - no component templates are created
4. run `GET _data_stream` - no data_stream are created
5. fields mapping are not correctly aligned with the component mapping templates

**What is the expected behavior?**
All the schema components should be created including
 - component mapping
 - index template
 - data_streams
 
**Do you have any screenshots?**

![](https://github.com/opensearch-project/dashboards-observability/assets/48943349/9b920adc-a7a2-49f9-8f60-47a10489b646)
![](https://github.com/opensearch-project/dashboards-observability/assets/48943349/766e0851-b637-48f1-be68-d705dc80bbcd)
![](https://github.com/opensearch-project/dashboards-observability/assets/48943349/43e45675-daf8-407f-87f9-130664a114f5)
![](https://github.com/opensearch-project/dashboards-observability/assets/48943349/b8831f22-e452-47c7-a07f-8f6e38a26b33)

**Comment by Swiddis** [comment]
Which integration is this for?

**Comment by YANG-DB** [comment]
Workaround :
For each integration within the config file (`integration_name-1.0.0.json`)
Update the `type:` value to correspond to the schema root log mapping container file name:
Example:
for aws_s3 that has an `log_s3-1.0.0.mapping` file, the type value should `logs_s3` instead of `loga`

This should be resolved in the future to be aligned with the same log index mapping template to be shared between all integrations and not having a dedicated version per integration

**Comment by derek-ho** [comment]
Completed by @Swiddis , closing, thanks!
