### ISSUE TITLE
[BUG] Integrations description text update

### ISSUE THREAD

**Issue by kavck** [opensearch-project/dashboards-observability#770]
**What is the bug?**
The description for the integrations page is incorrect.

**How can one reproduce the bug?**
1. Open the left navigation panel in OpenSearch
2. Select the “Integrations” navigation path

**What is the expected behavior?**
Modify the Integrations description text to the following:
“View integrations with preconfigured assets immediately within your OpenSearch setup. Learn more [external-link-icon]”

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/dashboards-observability/assets/108144351/f04a5883-8dc1-4de2-a124-bd9c9cda81fa)

**Comment by derek-ho** [comment]
Closing as done
