### ISSUE TITLE
[BUG] `class_cast_exception` attempting to index a trace document

### ISSUE THREAD

**Issue by MaxKsyunz** [opensearch-project/dashboards-observability#786]
**What is the bug?**
OpenSearch generates an exception when I try to index a trace from opentelemetry-collector.

**How can one reproduce the bug?**

Send the following document to OpenSearch node that does not have ss4o_traces-t-a index
```json
 {
          "attributes": {
            "data_stream": {
              "dataset": "default",
              "namespace": "namespace",
              "type": "span"
            },
            "http.flavor": "1.1",
            "http.method": "GET",
            "http.response_content_length": 11,
            "http.status_code": 200,
            "http.url": "http://demo-server:7080/hello",
            "net.peer.name": "demo-server",
            "net.peer.port": 7080
          },
          "droppedAttributesCount": 0,
          "droppedEventsCount": 0,
          "droppedLinksCount": 0,
          "endTime": "2023-07-31T16:45:20.599043855Z",
          "instrumentationScope": {
            "droppedAttributesCount": 0,
            "name": "go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp",
            "schemaUrl": "",
            "version": "0.42.0"
          },
          "kind": "Client",
          "name": "HTTP GET",
          "parentSpanId": "c9820c4fcb181475",
          "resource": {
            "host.name": "d4d3cf05c754",
            "process.command_args": [
              "/app/main"
            ],
            "process.executable.name": "main",
            "process.executable.path": "/app/main",
            "process.owner": "root",
            "process.pid": 1,
            "process.runtime.description": "go version go1.20.6 linux/amd64",
            "process.runtime.name": "go",
            "process.runtime.version": "go1.20.6",
            "service.name": "demo-client",
            "telemetry.sdk.language": "go",
            "telemetry.sdk.name": "opentelemetry",
            "telemetry.sdk.version": "1.16.0"
          },
          "spanId": "ae9dde3a42273a8b",
          "startTime": "2023-07-31T16:45:19.863862547Z",
          "status": {
            "code": "Unset",
            "message": ""
          },
          "@timestamp": "2023-07-31T16:45:19.863862547Z",
          "traceId": "2566150bc56619c53fc89b052eaba4f5",
          "traceState": ""
        }
```

e.g. `echo '<bad_json>' | curl -X POST -H 'Content-Type:application/json' -d @- http://localhost:9200/ss4o_traces-t-a/_doc`

results in the following error from OpenSearch:
```json
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse",
    "caused_by": {
      "type": "class_cast_exception",
      "reason": "class org.opensearch.index.mapper.KeywordFieldMapper cannot be cast to class org.opensearch.index.mapper.ObjectMapper (org.opensearch.index.mapper.KeywordFieldMapper and org.opensearch.index.mapper.ObjectMapper are in unnamed module of loader 'app')"
    }
  },
  "status": 400
}
```

The document is indexed successfully when it's sent to an index that does not match SS4O index template.

**What is the expected behavior?**
Document index correctly.

**What is your host/environment?**
OpenSearch 2.8 and 2.9

**Comment by MaxKsyunz** [comment]
There is no stacktrace in OpenSearch logs so I can't say where exactly the error is coming from.

@YANG-DB is this the right repo for this bug?

**Comment by derek-ho** [comment]
Most likely this is related to the ss4o index template - @YANG-DB assigning to you. I think https://github.com/opensearch-project/observability would be more appropriate, but we can raise an issue there after triaging further

**Comment by YANG-DB** [comment]
we are in the middle of transition from the exiting schema location ([each integration has a declared it own schema](https://github.com/opensearch-project/dashboards-observability/tree/main/server/adaptors/integrations/__data__/repository)) to the standard [catalog schema location](https://github.com/opensearch-project/opensearch-catalog/tree/main/schema/observability)
We will introduce a unified API that generates the correct mapping...
Can you please verify with the latest catalog mapping schema and create an issue for the [trace mapping schema] if necessary ?(https://github.com/opensearch-project/opensearch-catalog/blob/main/schema/observability/traces/traces.mapping)
