### ISSUE TITLE
[BUG]Update apache integration sourceUrl 

### ISSUE THREAD

**Issue by YANG-DB** [opensearch-project/dashboards-observability#810]
**What is the bug?**
Apache integration sourceUrl is pointing to a wrong integration

**How can one reproduce the bug?**
Apache integration sourceUrl is pointing to a wrong [integration](https://github.com/opensearch-project/dashboards-observability/blob/7f5cfe7d0d253533db1e2f2447940ad009942fa3/server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json#L9) 

**What is the expected behavior?**
Need to replace the url with the correct location

**Do you have any additional context?**
https://github.com/opensearch-project/dashboards-observability/blob/7f5cfe7d0d253533db1e2f2447940ad009942fa3/server/adaptors/integrations/__data__/repository/apache/apache-1.0.0.json#L9

**Comment by derek-ho** [comment]
Looks like this was done, thanks @danieldong51
