### ISSUE TITLE
Add support for jaeger schema [FEATURE]

### ISSUE THREAD

**Issue by anirudha** [opensearch-project/dashboards-observability#83]
**Is your feature request related to a problem?**
A clear and concise description of what the problem is, e.g. _I'm always frustrated when [...]_

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by kamingleung** [comment]
@derek-ho Thanks for your updates. A few comments:

1. How does the data source selector look like when users pick another data source? Can you post screenshots or video of how it works?
2. Are Traces and Services pages showing traces and services from the selected data source? We should have the same selector in Traces and Services pages as well.
3. On the Trace analytics/Dashboard page, there is an extra container, can we remove that? Screenshot:
![image](https://user-images.githubusercontent.com/3692324/210635571-c6bdbba7-56f8-4895-b4f6-d1e47ecdec32.png)

**Comment by derek-ho** [comment]
@kamingleung this is what it looks like without the extra container - is that better? I have also attached a screenshot of what it looks like when you hit the selector to change the data source selector. I will add it to each of the sub pages as well. The interaction diagram I had with Kyle last would have us keep both options there even if they don't have them and default to the data prepper or the one that they have. This way users will know about this new functionality (see the figma and let me know if you are on the same page as well). I will post a final walkthrough video after reviewing with @joshuali925 today for go/no-go for the next release.
![Screen Shot 2023-01-05 at 9 29 18 AM](https://user-images.githubusercontent.com/26328171/210803416-35396d4d-0334-42b5-b266-9206c0a8ee25.png)
![Screen Shot 2023-01-05 at 9 30 53 AM](https://user-images.githubusercontent.com/26328171/210803822-e751523c-6038-475d-bd3c-0b47119ab0f7.png)

**Comment by elfisher** [comment]
Hey @anirudha and @derek-ho confirming this is the right issue to add to the roadmap for the 2.5.0 release? Can we add the labels "2.5.0" and "roadmap"? I can get this added to the roadmap once those labels are added.

**Comment by derek-ho** [comment]
@elfisher I am doing some last minute performance testing with @joshuali925 before we can give the no-no go for release, will keep this updated thanks

**Comment by derek-ho** [comment]
Integration of trace flyout with event analytics
https://user-images.githubusercontent.com/26328171/211402354-43073892-0acb-4aa7-83db-5e4bae0917f9.mov
