### ISSUE TITLE
[BUG] Update secondary action in Integration details page

### ISSUE THREAD

**Issue by kavck** [opensearch-project/dashboards-observability#910]
**What is the bug?**
The "Try it" button in the Integrations detail page needs color prop updated to "secondary".

**How can one reproduce the bug?**
1. Go to Integrations
2. Click on Available tab
3. Click on NginX Dashboard
4. View "Try it" button

**What is the expected behavior?**
The "Try it" OuiButton should be using the "secondary" color property as the secondary action on the page (see screenshot below for positioning).

**Do you have any screenshots?**
![image](https://github.com/opensearch-project/dashboards-observability/assets/108144351/e786bbd1-aca0-422e-857a-0216e09fde52)

**Comment by Swiddis** [comment]
Resolved by #887
