### ISSUE TITLE
[FEATURE] Remove Zepellin Notebook backend

### ISSUE THREAD

**Issue by derek-ho** [opensearch-project/dashboards-observability#955]
**Is your feature request related to a problem?**
Seems like we are never using "Zepellin" Notebook backend - can it be removed?

**What solution would you like?**

**What alternatives have you considered?**

**Do you have any additional context?**

**Comment by pjfitzgibbons** [comment]
Fixed by https://github.com/opensearch-project/dashboards-observability/pull/985
